[package]
name = "memobits"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = { version = "0.16.0", optional = true }
rustyline = { version = "13.0.0", optional = true }

[features]
default = ["std"]
std = ["logos", "rustyline"]
